/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueadero;

import Vehiculos.Moto;

/**
 *
 * @author Estudiantes
 */
public class FichaVehiculo extends javax.swing.JFrame {
    
    Moto miMotoEnFichaVehiculo = new Moto();


    public FichaVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoMarca = new javax.swing.JTextField();
        boton1 = new javax.swing.JButton();
        textoMarca1 = new javax.swing.JTextField();
        textoMarca2 = new javax.swing.JTextField();
        textoMarca3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Cilindraje = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoMarca.setText("jTextField1");
        textoMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoMarcaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoMarcaMouseExited(evt);
            }
        });

        boton1.setText("Guardar");
        boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton1MouseEntered(evt);
            }
        });

        textoMarca1.setText("jTextField1");
        textoMarca1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoMarca1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoMarca1MouseExited(evt);
            }
        });

        textoMarca2.setText("jTextField1");
        textoMarca2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoMarca2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoMarca2MouseExited(evt);
            }
        });

        textoMarca3.setText("jTextField1");
        textoMarca3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoMarca3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoMarca3MouseExited(evt);
            }
        });

        jLabel1.setText("Marca:");

        Cilindraje.setText("Cilindraje;");

        jLabel2.setText("Año");

        jLabel3.setText("Modelo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(boton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(Cilindraje))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoMarca3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoMarca1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoMarca2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoMarca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cilindraje))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoMarca2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoMarca3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addComponent(boton1)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoMarcaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoMarcaMouseEntered

    }//GEN-LAST:event_textoMarcaMouseEntered

    private void textoMarcaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoMarcaMouseExited
        
        textoMarca.setText("Saliste");
        
        boton1.setVisible(true);
    }//GEN-LAST:event_textoMarcaMouseExited

    private void boton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseEntered

    }//GEN-LAST:event_boton1MouseEntered

    private void textoMarca1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoMarca1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_textoMarca1MouseEntered

    private void textoMarca1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoMarca1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_textoMarca1MouseExited

    private void textoMarca2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoMarca2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_textoMarca2MouseEntered

    private void textoMarca2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoMarca2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_textoMarca2MouseExited

    private void textoMarca3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoMarca3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_textoMarca3MouseEntered

    private void textoMarca3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoMarca3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_textoMarca3MouseExited

    private void boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseClicked
        
        this miMotoEnFichaVehiculo 
    }//GEN-LAST:event_boton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichaVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cilindraje;
    private javax.swing.JButton boton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textoMarca;
    private javax.swing.JTextField textoMarca1;
    private javax.swing.JTextField textoMarca2;
    private javax.swing.JTextField textoMarca3;
    // End of variables declaration//GEN-END:variables
}
